# Generated by Django 4.2.2 on 2023-07-22 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('room_name', models.CharField(max_length=150)),
                ('room_type', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
            ],
        ),
    ]
