# Generated by Django 4.2.3 on 2023-12-16 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventbooking', '0002_rename_arrivaldate_eventbooking_bookingdate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventbooking',
            old_name='BookingDate',
            new_name='ArrivalDate',
        ),
    ]
