# Generated by Django 4.2.1 on 2023-08-12 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=100)),
                ('Email', models.TextField()),
                ('ContactNo', models.TextField()),
                ('ArrivalDate', models.TextField()),
                ('DepartureDate', models.TextField()),
                ('Price', models.TextField()),
            ],
        ),
    ]
