# Generated by Django 4.2.1 on 2023-11-19 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='outdoorbooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=300)),
                ('Email', models.CharField(max_length=100)),
                ('ContactNo', models.CharField(max_length=200)),
                ('Package', models.CharField(max_length=200)),
                ('ArrivalTime', models.TimeField()),
                ('DepartureTime', models.TimeField()),
                ('Price', models.FloatField()),
            ],
        ),
    ]
