# Generated by Django 4.2.3 on 2023-12-17 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outdoorbooking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outdoorbooking',
            name='DepartureTime',
            field=models.DateField(),
        ),
    ]
