# Generated by Django 4.2.3 on 2023-12-17 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outdoorbooking', '0002_alter_outdoorbooking_departuretime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outdoorbooking',
            old_name='DepartureTime',
            new_name='ArrivalDate',
        ),
    ]
